language: node_js

node_js:
  - 8

script:
  - npm run build

deploy:
  provider: heroku
  api_key:
    secure: $KEY
  app: graphql-react-apollo
  on:
    repo: akilananb/graphql-react-apollo

branches:
  only:
  - deploy